test_file: overpotential.csv
test:
  max_test_time: 10000.0
  min_test_voltage: 1.0
  max_test_voltage: 1.5
  time_step: 0.1
  plot_points: 1100
hardware:
  shunt_resistance: 0.25
  v1_bias: 0.0
  v2_bias: 0.0
  capacity: 800
